### ISSUE TITLE
adding indexer scenenzb returns 403

### ISSUE THREAD

**Issue by frumpymoons** [theotherp/nzbhydra2#366]
Adding the indexer https://scenenzb.com returns 403.

```
019-04-19 15:32:15.083 ERROR --- [pool-3-thread-1] org.nzbhydra.okhttp.WebAccess            : URL call to https://scenenzb.com/api?t=search returned 403:
```

Adding the indexer in Radarr works fine.

I use the following Docker configuration:
```
  nzbhydra:
    container_name: nzbhydra2
    image: linuxserver/hydra2
    restart: unless-stopped
    networks:
      - internal
      - proxy
    volumes:
      - /opt/docker/nzbhydra2:/config
    environment:
      - PGID=1100
      - PUID=1100
      - TZ=Europe/Berlin
    labels:
      - traefik.frontend.rule=Host:nzbhydra.<mydomain>
      - traefik.docker.network=proxy
      - traefik.port=5076
```

[nzbhydra-debuginfos-2019-04-19-15-34.zip](https://github.com/theotherp/nzbhydra2/files/3098273/nzbhydra-debuginfos-2019-04-19-15-34.zip)
