### ISSUE TITLE
Message: undefined

### ISSUE THREAD

**Issue by modem7** [theotherp/nzbhydra2#844]
Similar issue to https://github.com/theotherp/nzbhydra2/issues/829

It seems to occur intermittently when downloading some nzbs using either SABNzbd button or the Results as ZIP button.

This however, still occurs even in incognito mode, where there should be no site data. 

![image](https://user-images.githubusercontent.com/4349962/217092628-5c7c41c3-3913-4552-a4cb-0e26ad72cc06.png)

Have also attempted to wipe all browser cookies and cache. 
This also occurs on multiple browsers (Have tried Vivaldi and Edge).

[nzbhydra-debuginfos-2023-02-06-21-25.zip](https://github.com/theotherp/nzbhydra2/files/10669300/nzbhydra-debuginfos-2023-02-06-21-25.zip)

This issue also seems to occur when attempting to upload debug logs (consistently). 

Server:
Hydra2 Version 5.1.1 (LSIO have not yet released 5.1.2).
Docker Version: 23.0.0 
Server OS: Ubuntu 22.04.1 LTS

Client:
Browser: Vivadi (Chrome)
Client OS: Windows 10

Compose YAML (excluding Traefik settings as this is being accessed locally currently):
```yaml
 #############
 ##NZBHydra2##
 #############

# NZBHydra2 - NZB meta search
  hydra2:
    image: linuxserver/nzbhydra2
    container_name: Hydra2
    hostname: Hydra2
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    networks:
      pihole:
        ipv4_address: '172.22.0.104'
    ports:
      - "5076:5076"
    healthcheck:
      test: curl -fSs 127.0.0.1:5076/actuator/health/ping || exit 1
      start_period: 60s
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - $USERDIR/NZBHydra:/config
      - $DOWNLOADDIR/downloads:/downloads
    restart: always
    mem_limit: 3000m
    mem_reservation: 250m
```

**Comment by theotherp** [comment]
Do you use a reverse proxy? I think that is adding trailing slashes to the URLs, e.g. `http://127.0.0.1:5076/internalapi/downloader/addNzbs` becomes `http://127.0.0.1:5076/internalapi/downloader/addNzbs/` and that isn't properly matched.

I'll fix it in hydra but please check anyway or see if you can fix it that way yourself because I'd like to see why this happens only for some users.

**Comment by modem7** [comment]
In this particular case, I was accessing it locally (http://serverIP:5076).

My full compose is:

```yaml
 #############
 ##NZBHydra2##
 #############

# NZBHydra2 - NZB meta search
  hydra2:
    image: linuxserver/nzbhydra2
    container_name: Hydra2
    hostname: Hydra2
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    labels: 
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.hydra-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.hydra-rtr-bypass.rule=Host(`hydra.$DOMAINNAME`) && Query(`apikey`, `$HYDRA_API_KEY`)"
      - "traefik.http.routers.hydra-rtr-bypass.priority=100"
      # - "traefik.http.routers.hydra-rtr-bypass.tls=true"
      ## HTTP Routers
      - "traefik.http.routers.hydra-rtr.entrypoints=https"
      - "traefik.http.routers.hydra-rtr.rule=Host(`hydra.$DOMAINNAME`)"
      # - "traefik.http.routers.hydra-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.hydra-rtr-bypass.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.hydra-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.hydra-rtr.middlewares=chain-authelia@file" # Authelia
      ## HTTP Services
      - "traefik.http.routers.hydra-rtr.service=hydra-svc"
      - "traefik.http.routers.hydra-rtr-bypass.service=hydra-svc"
      - "traefik.http.services.hydra-svc.loadbalancer.server.port=5076"
      ## Flame Dashboard
      - flame.type=application # "app" works too
      - flame.name=NZBHydra2
      - flame.category=Media
      - flame.icon=https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/nzbhydra2.png # Optional, default is "docker"
    networks:
      pihole:
        ipv4_address: '172.22.0.104'
    ports:
      - "5076:5076"
    healthcheck:
      test: curl -fSs 127.0.0.1:5076/actuator/health/ping || exit 1
      start_period: 60s
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - $USERDIR/NZBHydra:/config
      - $DOWNLOADDIR/downloads:/downloads
    restart: always
    mem_limit: 3000m
    mem_reservation: 250m
```
